@component('mail::message')
# Application Status Update

Hello **{{ $application->applicant_name }}**,

We are writing to inform you that there has been an update to your application. Your application has been **{{ strtoupper($action) }}** by the {{ $role }}.

@component('mail::panel')
### Application Summary
**Reference Number:** {{ $application->reference_number }}<br>
**Application Type:** {{ $application->application_type }}
@endcomponent

@if($remarks)
**Remarks from the {{ $role }}:**
> *{{ $remarks }}*
@endif

@if($action === 'Returned' || $action === 'Rejected')
Please log in to your account to review the specific notes and take the necessary next steps.

@component('mail::button', ['url' => route('login'), 'color' => 'error'])
Log In to Review
@endcomponent
@elseif($action === 'Approved')
Your application has successfully cleared this stage!

@endif

Thank you for your cooperation.

Best regards,<br>
**{{ config('app.name') }}**

---
*<small>This is an automated message generated by the system. Please do not reply directly to this email.</small>*
@endcomponent